unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

bind '-' split-window -v -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"
bind 'c' new-window -c "#{pane_current_path}"

unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind Left resize-pane -L 10
bind Right resize-pane -R 10
bind Down resize-pane -D 10
bind Up resize-pane -U 10

set -g mouse on

unbind-key -T copy-mode-vi MouseDragEnd1Pane

# bind-key -T copy-mode-vi v send -X begin-selection
# bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
# bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
# bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode.

set-option -g renumber-windows on

set -g status-bg "#121212"
set -g status-justify "centre"
set -g status-left-length "100"
set -g status "on"
set -g status-right-length "100"
setw -g window-status-separator ""
set -g status-left " #S "
setw -g window-status-format "  #I  "
setw -g window-status-current-format "#[fg=colour190,bg=#121212]  #I  #[default]"

set -g status-right "#[bg=#121212]%Y-%m-%d %H:%M#[default]"

set-option -g history-limit 99999
set-option -g status-position top
